"use client";
import { motion } from "framer-motion";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    id: "1",
    question: "What exactly does Scopeout do?",
    answer:
      "Scopeout is an AI-powered research intelligence platform. You type a name or topic, and our AI scrapes public sources — Google Scholar, LinkedIn, ResearchGate, university pages — then returns ranked, structured briefs about people. Each brief includes a compatibility score, a plain-English research summary, and a personalised conversation opener.",
  },
  {
    id: "2",
    question: "Which sources does Scopeout pull from?",
    answer:
      "We currently aggregate from Google Scholar, LinkedIn, ResearchGate, university faculty pages, and general web sources. On the Professional plan you can filter by specific sources or enable 'All Web' mode for a broader sweep.",
  },
  {
    id: "3",
    question: "How accurate are the match scores?",
    answer:
      "Match scores are generated by comparing your stated interests or background against the target's publication history, research topics, and public statements. Internal testing shows ~95% alignment with expert human rankings — though we always recommend reading the full brief before drawing conclusions.",
  },
  {
    id: "4",
    question: "Who is Scopeout built for?",
    answer:
      "Three main groups: PhD applicants who need to identify and pitch the right supervisors, job seekers and recruiters who want pre-interview intelligence on the other side of the table, and sales professionals who need prospect briefs before cold outreach or calls.",
  },
  {
    id: "5",
    question: "Is the data Scopeout uses private or sensitive?",
    answer:
      "Scopeout only aggregates publicly available information — the same data anyone could find with a few hours of manual searching. We do not access private profiles, paid databases, or internal company systems. All processing complies with GDPR and relevant data protection frameworks.",
  },
  {
    id: "6",
    question: "What's included in the free plan?",
    answer:
      "The free plan gives you 5 searches per month with basic researcher profiles and match scoring using Google Scholar as the primary source. It's ideal for occasional use or to evaluate whether Scopeout fits your workflow before upgrading.",
  },
  {
    id: "7",
    question: "Can I export the briefs Scopeout generates?",
    answer:
      "Yes — PDF export is available on the Professional plan and above. Enterprise users also get CSV export and webhook delivery so briefs can be piped directly into your CRM or ATS.",
  },
  {
    id: "8",
    question: "How do I get started?",
    answer:
      "Hit the search bar on the homepage, type a name or research topic, select your field and preferred sources, and press Enter. No account required for your first search. Sign up to save history and unlock more searches.",
  },
];

const half = Math.ceil(faqs.length / 2);
const leftCol  = faqs.slice(0, half);
const rightCol = faqs.slice(half);

export default function FAQ() {
  return (
    <section className="bg-transparent py-20 md:py-28 px-6 md:px-12 border-t border-white/5">
      <div className="max-w-6xl mx-auto">
        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.7, ease: [0.16, 1, 0.3, 1] }}
          viewport={{ once: true }}
          className="flex flex-col items-center text-center max-w-xl mx-auto mb-14"
        >
          <span className="text-orange-500 text-sm font-semibold uppercase tracking-widest mb-2">
            FAQ
          </span>
          <h2 className="text-4xl md:text-5xl font-bold text-white tracking-tight leading-tight">
            Everything you need to know
          </h2>
          <p className="text-gray-400 mt-4 leading-relaxed">
            Can't find your answer? Drop us a message and we'll get back within 24 hours.
          </p>
        </motion.div>

        {/* Two-column accordion */}
        <div className="grid md:grid-cols-2 gap-x-12">
          {[leftCol, rightCol].map((col, ci) => (
            <motion.div
              key={ci}
              initial={{ opacity: 0, y: 16 }}
              whileInView={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.5, delay: ci * 0.1, ease: "easeOut" }}
              viewport={{ once: true }}
            >
              <Accordion type="single" collapsible defaultValue={ci === 0 ? "1" : undefined}>
                {col.map((item) => (
                  <AccordionItem key={item.id} value={item.id}>
                    <AccordionTrigger>{item.question}</AccordionTrigger>
                    <AccordionContent>{item.answer}</AccordionContent>
                  </AccordionItem>
                ))}
              </Accordion>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
